### ISSUE TITLE
netd clobbers the whole FW mark when restoring the CONNMARK

### ISSUE THREAD

**Issue by fasaxc** [GoogleCloudPlatform/netd#105]
While testing Calico with intra-node visibility enabled, we spotted a subtle incompatibility:

* Calico uses mark bits to communicate between the various iptables chains.  For example, if "pre-DNAT" policy accepts a packet then a flag bit is set in the mangle-PREROUTING chain to tell the downstream "normal" policy that the packet was pre-approved by the earlier policy.

* netd stores and retrieves mark bits in the connection tracking mark.  While it only seems to use one or two bits of the connmark, it uses a `--restore -mark` operation with no mask to copy the connmark to the fw mark.  Since Calico's mark bits are per-packet and we don't store them in the connmark, this restore operation can clobber Calico's flag bits.

So, if the user uses certain combinations of Calico policy and intra-node visibility, they can get unexpected results.  Calico's eBPF dataplane also uses mark bits per-packet and these can also be clobbered.

I suggest using a mask on the restore operation so that Calico and netd can each manage their own ranges of bits.

**Comment by MrHohn** [comment]
Thanks for the details @fasaxc.

I think the problematic restore operation is from this line: https://github.com/GoogleCloudPlatform/netd/blob/bb7ed6b869acb64fedddd24de9df7ba8ae431684/pkg/config/config_policy_routing.go#L113

Will be looking to fix that soon.

/assign

**Comment by fasaxc** [comment]
@MrHohn just following up to see if you'd had time to fix this up.  Would it help for my team to put up a PR or would that just make more work for you?!

**Comment by fasaxc** [comment]
@MrHohn I put up PR #106; I'm not sure how to test "in anger" since this is effectively a locked down part of GKE.
