### ISSUE TITLE
PR #31 shouldn't generate the template at /etc/cni/net.d/

### ISSUE THREAD

**Issue by cadmuxe** [GoogleCloudPlatform/netd#43]
https://github.com/GoogleCloudPlatform/netd/pull/31
Calico is not looking for the existing .conflist.
maybe the config should go to g3/calico-node-daemonset-template.yaml.in instead?

**Comment by varunmar** [comment]
We set the CNI_NETWORK_CONFIG_FILE to the same .conflist file as netd. That is wrong, and we should move it somewhere else.
