### ISSUE TITLE
Repository needs continuous integration

### ISSUE THREAD

**Issue by bowei** [GoogleCloudPlatform/netd#54]
We need to have prow enabled on this repo.

Also, basic tests need to be run on submit:
* unit tests
* golint
* govet

**Comment by cadmuxe** [comment]
https://github.com/kubernetes/test-infra/pull/10376 configed the prow.

**Comment by cadmuxe** [comment]
https://github.com/kubernetes/test-infra/pull/10379
config the auto merge

**Comment by cadmuxe** [comment]
unit tests was covered by Travis CI
