### ISSUE TITLE
`noSnat` doesn't exist in portmap

### ISSUE THREAD

**Issue by Random-Liu** [GoogleCloudPlatform/netd#60]
The field `noSnat` doesn't exist in portmap.
https://github.com/GoogleCloudPlatform/netd/blob/master/netd.yaml#L90

There is only `snat`, and the default value is `true`. https://github.com/containernetworking/plugins/blob/696b1f9ab1022c34e1514e0e29bf84bb9179899f/plugins/meta/portmap/README.md#usage

What is the intended behavior? Will this cause any issue?

**Comment by Random-Liu** [comment]
@cadmuxe

**Comment by Random-Liu** [comment]
@jingax10

**Comment by Random-Liu** [comment]
@lzang

**Comment by lzang** [comment]
This looks an error to me, and it didn't take effect.

**Comment by varunmar** [comment]
I this has been fixed already - can we close this issue?

**Comment by cadmuxe** [comment]
Fixed with https://github.com/GoogleCloudPlatform/netd/pull/63
