### ISSUE TITLE
Adding an option to chain Cilium CNI

### ISSUE THREAD

**Issue by Weil0ng** [GoogleCloudPlatform/netd#80]
Hi, can we please add an option `enable_cilium` to cni-install.sh for the purpose of using netd along with cilium?

**Comment by varunmar** [comment]
SGTM. I suggest we use an env variable though, like all the other options already in there.

**Comment by Weil0ng** [comment]
Thanks! Yea that was the idea, I guess `option` is bad wording, I was thinking a knob similar to `enable_calico_policy` env :) Will prepare a PR then.

**Comment by Weil0ng** [comment]
Fixed by PR #81 . Close.
