### ISSUE TITLE
Silently overriding ENABLE_CALICO_NETWORK_POLICY behavior

### ISSUE THREAD

**Issue by bcheung** [GoogleCloudPlatform/netd#91]
The behavior introduced in #78 overrides `ENABLE_CALICO_NETWORK_POLICY` if netd does not detect Calico's CNI config file:
https://github.com/GoogleCloudPlatform/netd/blob/fef8459a0dcaa45965b0119137062206963654ed/scripts/install-cni.sh#L17-L33

If Calico CNI fails to install, why would we allow netd to proceed with GKE?
If the user intentionally set `ENABLE_CALICO_NETWORK_POLICY` to `true`, then silently changing this variable to `false` might make it difficult for the user to detect that the node is not using Calico as intended. This behavior seems "silent" because it just logs in a passive way (no error logs or alerts).

I can see why we may not want to exit with error since Kubernetes would repeatedly restart the Pod until the init container succeeds. However, would it be better to wait indefinitely until netd detects Calico's CNI config file since the user had to intentionally set `ENABLE_CALICO_NETWORK_POLICY` to `true`? 
At least in this case, if Calico CNI fails to install, we can see that the init container is still running and no application pods would be scheduled since kubelet cannot detect a vaild CNI config file. This would be more visible to the user to see that no application pods are running and they should fix Calico CNI's deployment so that the node uses Calico CNI as intended by the user.

**Comment by bcheung** [comment]
Connected with @lzang offline and found out that this behavior was implemented to serve a GKE-specific case.
The user runs this command to set `ENABLE_CALICO_NETWORK_POLICY` to `true` in netd and deploy Calico CNI:
```
gcloud container clusters update cluster-name --update-addons=NetworkPolicy=ENABLED
```
then the user must run this command to restart the node with new labels that enable network policy:
```
gcloud container clusters update cluster-name --enable-network-policy
```
---
If the user wants to disable calico network policy, they have to run the commands in the opposite order because disabling Calico CNI network policy on a running node is not safe.
This command restarts the node with labels so that Calico CNI network policy is not used:
```
gcloud container clusters update cluster-name --no-enable-network-policy
```
At this point, netd is still running with the same configuration with `ENABLE_CALICO_NETWORK_POLICY` to `true`.
Then the user must run this command to delete the Calico CNI deployments:
```
gcloud container clusters update cluster-name --update-addons=NetworkPolicy=DISABLED
```
However, since netd is already running, this command can't just update that environment variable, so netd does that itself by timing out after 2 minutes if Calico CNI is not installed.

More info: https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy

**Comment by lzang** [comment]
Yes, the code mentioned in this issue is for the disable process. After the first command `gcloud container clusters update cluster-name --no-enable-network-policy`, nodes restarted to disable Calico CNI, but netd still runs with the old configuration. The code ensures that the node can get ready in this case. Then user run the second command  `gcloud container clusters update cluster-name --update-addons=NetworkPolicy=DISABLED` to remove calico deployments and fix the netd configuration.

**Comment by jingyuanliang** [comment]
I think there's no action item here. Closing this issue. Adding a link to this issue in https://github.com/GoogleCloudPlatform/netd/pull/164.
